# Generated by Django 4.2.11 on 2024-05-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='comment_images/')),
                ('content', models.TextField(max_length=1000)),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['rating', 'target', 'author'],
            },
        ),
    ]
