# Generated by Django 4.2.11 on 2024-05-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('book', 'book'), ('movie', 'movie'), ('restaurant', 'restaurant')], default='', max_length=20),
        ),
    ]
