# Generated by Django 4.2.11 on 2024-05-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0002_comment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['rating', 'title', 'author']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='target',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('book', 'book'), ('movie', 'movie')], default='', max_length=20),
        ),
    ]
