# Generated by Django 4.2.11 on 2024-05-27 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anyrating', '0003_alter_comment_options_rename_target_comment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('book', 'book'), ('restaurant', 'restaurant')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
