# Generated by Django 4.2.11 on 2024-05-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0005_alter_comment_options_alter_comment_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-rating', 'category', 'author']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('restaurant', 'restaurant'), ('book', 'book')], default='', max_length=20),
        ),
    ]
