# Generated by Django 4.2.11 on 2024-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0006_alter_comment_options_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('movie', 'movie'), ('book', 'book'), ('restaurant', 'restaurant')], default='', max_length=20),
        ),
    ]
