# Generated by Django 4.2.11 on 2024-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0007_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('book', 'book'), ('movie', 'movie')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
