# Generated by Django 4.2.11 on 2024-05-28 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0008_alter_comment_category_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 11, 53, 44, 965118)),
        ),
    ]
