# Generated by Django 4.2.11 on 2024-05-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0009_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('book', 'book'), ('movie', 'movie'), ('restaurant', 'restaurant')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
