# Generated by Django 4.2.11 on 2024-05-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0010_alter_comment_category_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie'), ('Restaurant', 'Restaurant')], default='', max_length=20),
        ),
    ]
