# Generated by Django 4.2.11 on 2024-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0011_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Movie', 'Movie'), ('Book', 'Book')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
