# Generated by Django 4.2.11 on 2024-05-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0013_alter_comment_category_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Movie', 'Movie'), ('Book', 'Book')], max_length=20),
        ),
    ]
