# Generated by Django 4.2.11 on 2024-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0015_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Restaurant', 'Restaurant'), ('Book', 'Book')], max_length=20),
        ),
    ]
