# Generated by Django 4.2.11 on 2024-05-28 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anyrating', '0022_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Book', 'Book'), ('Restaurant', 'Restaurant')], max_length=20),
        ),
    ]
