# Generated by Django 4.2.11 on 2024-05-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0023_alter_comment_author_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Book', 'Book'), ('Movie', 'Movie')], max_length=20),
        ),
    ]
