# Generated by Django 4.2.11 on 2024-05-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0028_comment_dummy_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Book', 'Book'), ('Restaurant', 'Restaurant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dummy',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
