# Generated by Django 4.2.11 on 2024-05-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0031_alter_comment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating_as_star',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Book', 'Book'), ('Movie', 'Movie')], max_length=20),
        ),
    ]
