# Generated by Django 4.2.11 on 2024-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0032_comment_rating_as_star_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Restaurant', 'Restaurant'), ('Book', 'Book')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating_as_star',
            field=models.TextField(default='', max_length=20),
        ),
    ]
