# Generated by Django 4.2.11 on 2024-05-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0034_alter_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating_as_star',
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Restaurant', 'Restaurant'), ('Movie', 'Movie')], max_length=20),
        ),
    ]
