# Generated by Django 4.2.11 on 2024-05-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0037_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Book', 'Book'), ('Movie', 'Movie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
