# Generated by Django 4.2.11 on 2024-05-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0038_alter_comment_category_alter_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Restaurant', 'Restaurant'), ('Movie', 'Movie')], max_length=20),
        ),
    ]
