# Generated by Django 4.2.11 on 2024-05-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0039_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Book', 'Book'), ('Movie', 'Movie'), ('Restaurant', 'Restaurant')], max_length=20),
        ),
    ]
