# Generated by Django 4.2.11 on 2024-06-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0042_alter_comment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Book', 'Book'), ('Movie', 'Movie')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
