# Generated by Django 4.2.11 on 2024-06-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyrating', '0043_alter_comment_category_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Movie', 'Movie'), ('Book', 'Book')], max_length=20),
        ),
    ]
